sudo: required

services:
    - docker

env:
    global:
        - IMAGE_TAG=patrickdappollonio/alpine-utils

script:
    - docker build --pull=true --rm=true -t $IMAGE_TAG .

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $IMAGE_TAG;
      fi
